#!/usr/bin/env bash

set -e
set -o pipefail

[ "$DOTFILES_PATH" ] || export DOTFILES_PATH="$(cd $(dirname "$0"); pwd)"

# Install Homebrew.
type -t brew > /dev/null || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install 'op' (1Password CLI) and jq to parse results.
type -t op > /dev/null || brew cask install 1password-cli
type -t jq > /dev/null || brew install jq

if ! mas account > /dev/null; then
    mas signin --dialog "$MAS_EMAIL"
fi

# If there is no existing 1Password session, prompt for details to signin.
if [ -z "$OP_SESSION_my" ]; then
    while [ -z "$OP_EMAIL" ]; do
        echo -n "1Password email address: "
        read OP_EMAIL
    done

    while [ -z "$OP_KEY" ]; do
        echo -n "1Password secret key (not your master password): "
        read OP_KEY
    done

    eval $(op signin my "$OP_EMAIL" "$OP_KEY")
fi

### END OF INTERACTIVE USAGE ###################################################

for FILE in "$DOTFILES_PATH/install.d/"*.bash; do
    echo ">>> sourcing $FILE"
    source "$FILE"
done
