#!/usr/bin/env bash
set -e
set -o pipefail

export GITHUB_USER=jmalloc
export DOTFILES_PATH="$HOME/grit/github.com/$GITHUB_USER/dotfiles"

export OP_ACCOUNT="$(echo 'dGVhbV9hd2t3YXJkCg==' | base64 --decode)"
export OP_EMAIL="$(echo 'bWFpbGphbWVzaGFycmlzQGdtYWlsLmNvbQo=' | base64 --decode)"

# Trigger installation of Xcode command-line tools.
if ! pkgutil --pkg-info=com.apple.pkg.CLTools_Executables > /dev/null; then
	echo "Triggering installation of Xcode command-line tools."
	git --version > /dev/null
else
	echo "Xcode command-line tools already installed."
fi

# Prompt immediately for sudo, and keep it alive while the install script runs
echo "Elevating to superuser permissions."
sudo -v # -v = update credential cache without executing a command
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

if hash brew 2>/dev/null; then
    echo "Homebrew already installed."
else
    echo "Installing Homebrew..."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if hash jq 2>/dev/null; then
    echo "jq already installed."
else
    echo "Installing jq..."
    brew install jq
fi

if hash mas 2>/dev/null; then
    echo "mas already installed."
else
    echo "Installing mas..."
    brew install mas
fi

if hash op 2>/dev/null; then
    echo "1Password CLI already installed."
else
    echo "Installing 1Password CLI..."
    brew cask install 1password-cli
fi

if cat ~/.op/config | jq --exit-status '.accounts | .[] | select(.shorthand == "'"$OP_ACCOUNT"'")' > /dev/null; then
    eval $(op signin "$OP_ACCOUNT")
else
    eval $(op signin "${OP_ACCOUNT//_/-}.1password.com" "$OP_EMAIL")
fi

if mas account; then
    echo "App store sign in detected."
else
    op get item --account=$OP_ACCOUNT "Apple ID (AU)" | jq --raw-output '.details.fields[]? | select(.designation == "password") | .value' | tr -d '\n' | pbcopy
    echo "Sign in to the app store first. Password has been copied to the clipboard."
    mas open
    open "x-apple.systempreferences:com.apple.preferences.AppleIDPrefPane"
    exit 1
fi

if [[ -d "$DOTFILES_PATH" ]]; then
    echo "Pulling $GITHUB_USER/dotfiles..."
    pushd "$DOTFILES_PATH" > /dev/null
    git pull
    popd > /dev/null
else
    echo "Cloning $GITHUB_USER/dotfiles..."
    git clone "https://github.com/$GITHUB_USER/dotfiles.git" "$DOTFILES_PATH"
fi

if [[ -e "$HOME/dotfiles" ]]; then
    echo "Dotfiles shortcut directory already exists."
else
    ln -s "$DOTFILES_PATH" "$HOME/dotfiles"
fi

for FILE in "$HOME/dotfiles/install.d/"*-*.bash; do
  source "$FILE"
done

echo "Done. System must be restarted for some changes to take effect."
