#!/bin/bash
set -e

# Make sure is run as root ...
if [[ $UID != 0 ]]; then
    sudo "$0" "$@"
    exit $?
fi

# Install all the things ...
port install \
    git-core \
    git-flow \
    hub \
    php55 \
    php55-curl \
    php55-http \
    php55-iconv \
    php55-intl \
    php55-mbstring \
    php55-mcrypt \
    php55-mysql \
    php55-openssl \
    php55-pcntl \
    php55-posix \
    php55-soap \
    php55-sqlite \
    php55-xdebug \
    php55-zip \
    subversion \
    nodejs \
    npm

cp res/php.ini /opt/local/etc/php55

mkdir -p /usr/local/bin

# Install composer ...
curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin
mv /usr/local/bin/composer.phar /usr/local/bin/composer

# Install phpunit ...
curl -s https://phar.phpunit.de/phpunit.phar -o /usr/local/bin/phpunit
chmod +x /usr/local/bin/phpunit

curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o /usr/local/bin/php-cs-fixer
chmod +x /usr/local/bin/php-cs-fixer

# Install node stuff ...
npm install -g coffee-script
