#!/bin/bash
set -e

# Make sure is run as root ...
if [[ $UID != 0 ]]; then
    sudo "$0" "$@"
    exit $?
fi

xcode-select -switch /usr/bin

port install \
    php54 \
    php54-apc \
    php54-curl \
    php54-http \
    php54-mbstring \
    php54-mcrypt \
    php54-mysql \
    php54-openssl \
    php54-pcntl \
    php54-posix \
    php54-soap \
    php54-xdebug \
    php54-zip \
    git-core \
    nodejs

port select php php54

mkdir -p /usr/local/bin

curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin
mv /usr/local/bin/composer.phar /usr/local/bin/composer

curl -s http://pear.phpunit.de/get/phpunit.phar -o /usr/local/bin/phpunit
chmod +x /usr/local/bin/phpunit
