cask_args appdir: "/Applications"

tap "datawire/blackbird"
tap "homebrew/cask-fonts"
tap "jmalloc/grit"
tap "ktr0731/evans"
tap "remotemobprogramming/brew"

# Install Binaries
brew "adr-tools"
brew "clang-format" # needed for VSCode protobuf extension to support formatting
brew "composer"
brew "direnv"
brew "grit"
brew "mas"
brew "node"
brew "php"
brew "telepresence-arm64"
brew "yarn"

# Install Apps
cask "1password-cli"
cask "1password"
cask "around"
cask "google-chrome"
cask "docker"
cask "visual-studio-code"
cask "zoom"

# Install Apps form the App Store
mas "Magnet", id: 441258766
mas "Parcel", id: 639968404
mas "Slack", id: 803453959

# Install Fonts
cask "font-meslo-for-powerline"
