cask_args appdir: "/Applications"

tap "homebrew/cask-fonts"

# Install Binaries
brew "clang-format" # needed for VSCode protobuf extension to support formatting
brew "composer"
brew "node"
brew "php"
brew "yarn"

# Install Apps
cask "docker"

# Install Fonts
cask "font-meslo-for-powerline"
