cask_args appdir: "/Applications"

tap "homebrew/cask-fonts"
tap "jmalloc/grit"

# Install Binaries
brew "git"
brew "go"
brew "grit"
brew "less" # required for the --quit-if-one-screen option to work properly
brew "node"
brew "terraform"
brew "yarn"

# Install Apps
cask "1password-cli"
cask "docker"
cask "kicad"
cask "visual-studio-code"

# Install Apps form the App Store
mas "1Password 7", id: 1333542190
mas "Brother P-touch Editor", id: 1453365242
mas "Logic Pro", id: 634148309
mas "Magnet", id: 441258766
mas "Parcel", id: 639968404
mas "Slack", id: 803453959

# Install Fonts
cask "font-meslo-for-powerline"
